### ISSUE TITLE
fairies ads

### ISSUE THREAD

**Issue by Hantuhantuhantu** [Tune389/Tap-Titans-2-Progress-Bot#42]
when ads fairies come up, bot stop and doing nothing please fix the bug thanks

**Comment by jayrc** [comment]
https://github.com/Tune389/Tap-Titans-2-Progress-Bot/issues/32

The issue is resolved in that thread:
"Click the "No Thanks" button when a fairy ad screen comes up.
You can add this code to the RANDOM ATTACK section in between the "Equipment Stacking" and the Touch.

   var #noThanksColor 0
   getColor #noThanksColor 134 620
   if #noThanksColor == 688378
          touchDown 0 134 620
          sleep #btnDelay
          #time = #time + #btnDelay
          touchUp 0
          sleep #btnDelay
          #time = #time + #btnDelay
   endif
"

**Comment by eljano** [comment]
thanks for help.
For me it's good but I see a big slow since I put this. 
It is normaly?
can you explane were we must add the script?
Thanks and sorry for my english ( I m french)

**Comment by zalupakiss** [comment]
Instead, change the value of var #focusMainHero 1 to var #focusMainHero 0.
It helped me.
### Let me know if this helped you.

**Comment by Hantuhantuhantu** [comment]
@zalupakiss that help thanks

**Comment by jayrc** [comment]
If this is resolved, please close the issue.
