### ISSUE TITLE
Just write the script yourself...

### ISSUE THREAD

**Issue by Zethu5** [Tune389/Tap-Titans-2-Progress-Bot#92]
The game was updated like a week ago (?) and I just knew that the original creato wont come to update the script.
I tried fixing his script with acouple of users here without success...
Sooo.... I've tried writing one myself and succeeded.
The bot i've written is running at full functionality and is very stable, not crashing, for about 13-14 hours now, I've fixed alot of bugs that were in the script.
It took me about 5 days and a total of 10-20 hours (not that much).
I'm sorry if it sounds like i'm bragging but i'm trying to suggest you to write a full script from 0.

The documentation is very understandable and the task is very possible!
I wont share my script but I hope someone will be up to the task and will write a script and distribute it :).

**Comment by atereshkov** [comment]
And what is the goal of your post? We have I guess a more or less working copy in the development branch.

**Comment by tommka** [comment]
Hmmm thanks thats very impressive.

**Comment by DaBest1Evar** [comment]
@Zethu5 what's the goal of this? Why would you hope for someone to distribute a script when there's a working copy in the development branch? A lot of people have come together and proposed a lot of fixes and my script is working good as new again. Why don't **you** be the person to share his completed script he started from scratch? Saying you won't share it but have allegedly already created one from the ground up and 'hope' someone else released a new script for unknown reasons is pretty dubious. A lot of people have had their personal scripts up and running due to everyone in the community offering fixes and help, there's honestly no reason for someone else to erect another script when there's already a well-developed one. It sounds like you want someone to make a script for you because you probably haven't at all created one.
